pipeline {
  agent any
  parameters {
      choice(name: 'ENV', choices: ['dev','prod'], description: 'Selecciona el entorno')
  }

  stages {

    stage('Check environment') {
      steps {
        echo 'Checking containers...'
        sh 'docker ps'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
        echo "Deploying Apache using Ansible to ${params.ENV}"
        sh """
          docker exec ansible-control bash -c \"
            cd /ansible/ansible &&
            ansible-playbook playbooks/deploy_apache.yml --limit ${params.ENV}
          \"
        """
      }
    }

  }
}